import fs from "fs";
import { DocumentNode } from "graphql";
import gql from "graphql-tag";
import path from "path";

let typeDefs: DocumentNode | null = null;

/**
 * Loads the Apollo GraphQL type definitions.
 */
export function getApolloTypeDefs() {
  if (typeDefs) return typeDefs;

  let schemaString: string;
  try {
    schemaString = fs.readFileSync(
      path.resolve(__dirname, "schema.graphql"),
      "utf8",
    );
  } catch (e) {
    throw new Error(`
Failed to read "schema.graphql". This file is generated by the tools script.

Error: ${e.message}
`);
  }

  typeDefs = gql`
    ${schemaString}
  `;
  return typeDefs!;
}
