# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.11-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - run:
          name: Update Yarn
          command: |
            curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.6.0

      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}

      # run tests!
      # - run: yarn test
      - run: yarn lint
      - run: yarn build

      # Deploy to staging
      - add_ssh_keys
      - run:
          name: Deploy
          command: |
            if [ $CIRCLE_BRANCH = 'master' ]
            then
              echo 'dev.bhartitest.com,45.77.116.238 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBNZ6XoTAtmf2P3fcxYqHpt1U5JQrPdURnaMU4XXkifUj0m7pCiQad4ltk8DpaO/0/zVHGMrcquUZJ7mUJFBrkXc=' >> ~/.ssh/known_hosts
              scp -r apps/user/build/* deploy@dev.bhartitest.com:/var/www/
              scp -r apps/storybook/dist/* deploy@dev.bhartitest.com:/var/www/storybook/
            fi
